### ISSUE TITLE
Migrating to TF2

### ISSUE THREAD

**Issue by yqshao** [Teoroo-CMC/PiNN#2]
Dear developers,

It's generally favorable to migrate to TF2, I'm aware of the following advantages

- A cleaned up API (eager execution, removal of sessions, etc).
- Built in support for using TensorBoard in Juptyer notebooks.
- Possibly improved performance.

After some further fixes (mostly cleaning of naming) and upgrading 
the current code base to TF1.15 (last 1.X) version, I'll try migrating 
the code to TF2.

I'll not likely start immediately, but welcome comments and suggestions.

**Comment by yqshao** [comment]
# Updates

We now have a running TF2.X version of PiNN. The code actually runs without too much problem in TF2 (70aac18) but I think it would be worthwhile to follow the 2.x logics to avoid future problems (0fd2ba6). Following is a list of planned changes:

### Layers are now keras Layers
TF2 removes the functional layers. Following that the PiNN layers(cell list, basis function, etc) are rewritten as Keras layers. This hopefully will make it easier to use those layers, e.g. 
```python
tensors = CellListNL(5)(inputs)
tensors.update(inputs)
tensors = BPSymmFunc(sf_spec, 5, 'f1', use_jacobian=True)(tensors)
tensors = BPFingerprint(sf_spec, nn_spec, [], False )(tensors)
output = BPFeedForward(nn_spec, act='tanh', out_units=1, out_pool=False)(tensors)
model = tf.keras.Model(inputs=inputs, outputs=output)

tf.keras.utils.plot_model(model, 'my_bpnnl.png')
```
![image](https://user-images.githubusercontent.com/22888066/78060770-69734880-738c-11ea-95de-8864db68b9c7.png)

### Networks are now keras Models
Following the changes of layers the networks are now implemented as Keras models. The change seems beneficial as now the networks can be directly used to predict some simple properties, making it easier for demonstrations and testing, e.g.
```python
>>> files = glob('/home/yunqi/datasets/QM9/dsgdb9nsd/*.xyz')[:1000]
>>> pinet = PiNet(out_pool='sum')
>>> pinet.compile(optimizer=tf.keras.optimizers.RMSprop(), loss='MAE')
>>> dataset = load_qm9(files, split=1).apply(sparse_batch(10)).map(label_data)
>>> pinet.fit(dataset, epochs=3)
```
````
Epoch 1/3
100/100 [==============================] - 7s 70ms/step - loss: 89.3480
Epoch 2/3
100/100 [==============================] - 3s 27ms/step - loss: 50.7640
Epoch 3/3
100/100 [==============================] - 3s 28ms/step - loss: 38.8219
```` 

It seems still tricky to use the keras Models for fancier tasks (like what's done in the potential and dipole model) so I think we'll keep the the `pinn.models` for those purposes.

### Models and datasets are mostly unchanged
It seems that TF2 does not change much about how estimators and datasets works. Therefore most of the scripts for production can be left unchanged. However, it seems better to save keras models directly now (compared to saving the network parameters), this remains to be tried.

# Todo list
- [ ] rework the documentation
  - [ ] showcase model building with Keras
  - [ ] showcase inline tensorboard
  - [ ] document the behavior of layers and with test cases
- [ ] Unit tests for individual layers
- [ ] Remove usage of `tf.compat.v1` in pinn.models
- [ ] Rework model saving protocol

**Comment by yqshao** [comment]
I was stuck for a while trying to have a working demo of (Keras+PiNN+PiNNboard)...  
Now we have a teaser for those who are interested: [<img src="https://colab.research.google.com/assets/colab-badge.svg?style=flat-square" >](https://colab.research.google.com/gist/yqshao/949bf977480fc97ac411968f82502279/pinnboard-demo.ipynb).

**Comment by yqshao** [comment]
An update after long, a functional version of PiNN v1.x (with TF2) is now is in the TF2 branch.
For the new version we plan to move most of the CI tasks to Github actions and documentation 
to Github pages. The CI and page is activated as of today.

A list of proposed API changes is now available at the new [documentation page](https://teoroo-cmc.github.io/PiNN/latest/migration/).
More documentation and testing is on their way, but meanwhile you are welcome
to try out the TF2 branch if you are interested, and give suggestions regarding the update or report bugs (before we release PiNN v1.0 officially)
